Custom style from shield.io and some refactoring
greenkeeperio/badges pull request #8
Opened 2017-08-15 02:56 UTC by uniibu

Status: 
- Travis-ci Build passed ![Travis-ci](https://travis-ci.org/uniibu/badges.svg?branch=master)

Major Changes:
- Added support to shields.io's style parameters and this should also satisfy https://github.com/greenkeeperio/greenkeeper/issues/416. With this PR, greenkeeper can now accept a `style` paramater and supports `flat` `flat-square` and `plastic` style from shields.io.
- Change the word `enabled` to `monitored`

Minor Changes:
- Refactored and rearranged some codes
- Changed 'Greenkeeper' word on the badge to the standard badge lettering  which is all lower-case.
- Added example badges on README
- Change left-side badge color to make the badge unique
- Added tests for the new style query
- Update Hapi.js version on the package.json
- Added package-lock.json on gitignore.
- Since the engine recommends the Node version to be 7, i would assume, its the latest of the v 7 releases, and version lower than 7.10.1 are labeled to be `high severity vulnerability` [july-2017-security-releases](https://nodejs.org/en/blog/vulnerability/july-2017-security-releases/#_-update-11-july-2017-_-security-releases-available), i've set the recommended version to `^7.10.1 || >= 8.1.4`
- And because of the node version change, `--harmony` flag is no longer needed, so i removed it.

Badges will look like the following:(flat-square,flat, plastic)

![Greenkeeper flat](https://img.shields.io/badge/greenkeeper-monitored-3b99ef.svg?colorA=00c775&style=flat-square) ![Greenkeeper NotFound](https://img.shields.io/badge/greenkeeper-not_found-E74C3C.svg?colorA=00c775&style=flat)  ![Greenkeeper Disabled](https://img.shields.io/badge/greenkeeper-disabled-808080.svg?colorA=00c775&style=plastic) 

PS. Feel free to edit ☺️

2017-08-20 04:29 UTC, levithomason commented
It would be great to get statuses similar to what gemnasium supports like "up to date" and "out of date".

May also consider sticking with the usual dark gray background on the left:

<img src=https://user-images.githubusercontent.com/5067638/29492084-2e5c184c-8525-11e7-9362-4f6aaafb5d3f.png width=570 />

>https://github.com/Semantic-Org/Semantic-UI-React

2017-08-21 16:04 UTC, j-f1 commented
Why not use the Greenkeeper green for the enabled/monitored background color? It’s already green, so it’d be less of a change. You could also change the left side to say “🌴 greenkeeper” to stay closer to the brand.

2017-12-18 16:43 UTC, kbrandwijk commented
I am a big fan of the 'for-the-badge' style. Any reason why that's not included?

2018-03-06 11:11 UTC, janl requested changes
Heya, thanks for taking the time to improve Greenkeeper, and apologies for the late response here.

This is a good addition overall, we just request a few style changes. I’ve added inline comments for the few details. If you could help clean up the commits a little bit, I’m sure we can get this merged quickly.

2018-03-06 11:11 UTC, janl commented on lib/badges.js
> -
Please do whitespace-only changes in a separate commit.

This allows us to skim over whitespace-only changes in larger functions (see below)

2018-03-06 11:11 UTC, janl commented on lib/badges.js
> -
Whitespace

2018-03-06 11:11 UTC, janl commented on lib/badges.js
> +const ghBadges = data =>
This is one of the candidates for why we prefer whitespace-only changes that don’t commit any functional changes:

 
![screen shot 2018-03-06 at 12 04 19](https://user-images.githubusercontent.com/11321/37029128-980e9b72-2136-11e8-9626-df0873b23a11.png)

2018-03-06 11:11 UTC, janl commented on lib/badges.js
> +const createHash = bytes => crypto.createHash('sha256').update(bytes).digest('hex')
This is a pure style change that makes the intent hard to follow as well.

2018-03-06 11:11 UTC, janl commented on lib/badges.js
> +  const getBadge = (repoDoc, payDoc, style) => {
Whitespace & Style-changes mixed with functional changes again.

2018-03-06 11:11 UTC, janl commented on lib/badges.js
> +    let repoDoc, payDoc
Whitespace again.

2018-03-06 11:11 UTC, janl commented on package.json
> -    "hapi": "^16.1.0",
Please add a reason for updating the hapi version? Are you using hapi features that are not available earlier?

Also, this should be a separate commit.

2018-03-06 11:11 UTC, janl commented on package.json
> -    "node": "7"
Please add a reason for updating the engine version? Are you using features that are not available earlier?

Also, this should be a separate commit.

2018-03-06 11:11 UTC, janl commented on package.json
> -    "start": "node --harmony_async_await index.js",
This goes with the engine-changes, should be separate from the main commit here.

2018-03-06 11:11 UTC, janl commented on test/badges.js
> -const dbs = require('../lib/dbs')
Whitespace again

2018-03-06 11:11 UTC, janl commented on .gitignore
> +package-lock.json
Why do you remove the package-lock.json?

2018-03-06 11:11 UTC, janl commented on .travis.yml
> +  - '8'
Greenkeeper ops is not running on node 8 just yet, so we’d rather keep an engine update out of this PR until we move over the whole project.

2018-03-06 11:11 UTC, janl commented on package.json
> +    "node": "^7.10.1 || >= 8.1.4"
Can you explain why these versions are picked exactly?

2018-03-08 08:21 UTC, uniibu commented
This pull request was from an older version of greenkeeperio/badges (Aug. 2017). Im closing this this pull request and creating a new one to keep things clean. I've also noted your comments @janl and will update accordingly. Cheers

2018-03-08 08:21 UTC, closed without merging